# Generated by Django 2.2 on 2020-08-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedcheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_supervisor',
            field=models.BooleanField(default=False, help_text='Designates whether user has supervisor status.', verbose_name='Supervisor Status'),
        ),
    ]
