# Generated by Django 2.2 on 2020-09-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bedcheck', '0002_user_is_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.TextField(blank=True, null=True)),
                ('bed_a', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bedcheck_room_bed_a', to='bedcheck.Client')),
                ('bed_b', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bedcheck_room_bed_b', to='bedcheck.Client')),
            ],
        ),
    ]
